### ISSUE TITLE
User Story 6: add delete button to asana-card in flow-page

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#13]
## Value Proposition
As a user I want to delete particular poses from my flow-list in order to not practice them.

## Description
![Wireframe_CP_US6](https://user-images.githubusercontent.com/111566392/196969673-7072df89-c6f6-4af6-b441-b2a812081d11.png)

## Acceptance Criteria
- [x] add a delete-button to the AsanaCard component 
- [x] when the button is clicked, the pose should be removed from the flow 

## Tasks
- [x] create new feature-branch
- [x] create a delete button
- [x] add the delete button to the AsanaCard component
- [x] add an onClickHandler to the button, that removes this particular card from the state 
- [x] conditionally render the delete button only on the flow-page
