### ISSUE TITLE
User Story 7: add search bar

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#14]
## Description

![Wireframe_CP_US7](https://user-images.githubusercontent.com/111566392/197217500-7a30419c-d74e-457b-9eba-c40337499fcf.png)

## Acceptance Criteria

- [x] display search bar in index page
- [x] display search bar in asana list in flow page
- [x] only asanas whose name matches the search query will be displayed
- [x] if no search query is submitted all asanas will be displayed

## Tasks

- [x] create new feature-branch
- [x] create search bar component with input field
- [x] add a search bar placeholder text
- [x] add search bar component to index
- [x] add search bar component to AddAsanaSection in flow.js
- [x] implement filter-function on input field based on search query
