### ISSUE TITLE
User Story 8: add filter for level

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#15]
## Value Proposition
As a user I would like to be able to filter the poses to see only those that match my level.

## Description

![Image](https://user-images.githubusercontent.com/111566392/198064448-c043b1c1-24ca-4ccd-9b80-6fc6ee0e54ac.png)

## Acceptance Criteria
- [x] display radio button filter in index page
- [x] display radio button filter in asana list in flow page
- [x] only asanas whose level matches the filter query will be displayed
- [x]  if no filter query is submitted all asanas will be displayed

## Tasks
- [x] create new feature-branch
- [x] create a filter component with radio buttons 
- [x]  add filter component to index
- [x]  add filter component to AddAsanaSection in flow.js
- [x] implement filter-function based on the value of the radio buttons
