### ISSUE TITLE
Add basic rules for styling and positioning 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#16]
## Value Proposition
As a user I want to have a consistent styling and good positioning of the elements so that I can have a good user experience.
 
## Description
All elements should have basic styling rules for padding, margin, colors, font-sizes etc. 

## Acceptance Criteria
- [x] elements should have a consistent look 
- [x] the elements should be placed so that everything is clearly visible and legible 

## Tasks
- [x] add css variables for color, background and drop-shadow to the root element in global styles
- [x] add basic rules for font-size and text-alignment to global styles
- [x] apply rules in styled components on all pages 
- [x] add grid positioning to AsanaCard component
- [x] improve positioning of DetailCard component
- [x] import and apply custom fonts for headline and body

**Comment by kai-franke** [comment]
There can't be enough beauty in the world. Have fun styling your app!
