### ISSUE TITLE
User Story 1: display yoga asanas on index page

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#2]
## Value Proposition
As a user, I want to see the yoga asanas with a picture and name so that I know, which asana I can practice.

## Description
![Screenshot 2022-10-14 at 14 28 03](https://user-images.githubusercontent.com/111566392/195846957-418daa35-1b15-4ec6-866b-d4a237859293.png)

## Acception Criteria
- [x] when the app is opened, a list of all the yoga asanas should be displayed 
- [x] every card shows a title (name of the asana) and a picture

## Tasks
- [x] create an array with objects for the yoga asana in the index.js
- [x] every object needs a property for name and image
- [x] create a component-folder 
- [x] create a card-component, which displays name and image of the object
- [x] map over the asanas-array and render the card-components in the index-page

**Comment by F-Kirchhoff** [comment]
This is a perfect user story, nothing to add here. You could have started with even a step before where you only display one card, but this is fine since the user story is still small enough. Top!
