### ISSUE TITLE
User Story 9: Create different flow-cards

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#20]
## Value Proposition
As a user I want to create different entries for different flows so that I can practice more than one. 

## Description
![Wireframe_CP_US9](https://user-images.githubusercontent.com/111566392/197565729-bd7dcdb7-13c6-4ae8-815c-35d57390dea4.png)

## Acceptance Criteria
- [x] A create-page should display a form to create a new flow 
- [x] when the user types in a name and submits the form a new card with the flow name is displayed
- [x] the form is only displayed when the user clicks on the plus button 

## Tasks
- [x] set up a new feature branch 
- [x] create a new page "create"
- [x] add a plus-button icon to the page 
- [x] add a form to the page 
- [x] add an input field (type text) and a submit button to the form 
- [x] catch the data from the form and render a flow-card-component with the name 
- [x] add conditional rendering so that the form is only displayed after clicking the plus icon
- [x] display 2 dummy flows
