### ISSUE TITLE
User Story 10: add dynamic routing from flow-card to flow-page

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#21]
## Value Proposition
As a user I want to set up my new flow in order to practice it. 

## Description
![Wireframe _CP_US10](https://user-images.githubusercontent.com/111566392/197571454-4bdc0f92-a7c5-4bb1-8e7f-b051c045cc81.png)

## Acceptance Criteria
- [x] when the user clicks on one of the flow-cards he is redirected to a page where he can set up his flow

## Tasks

- [x] create a new branch dynamic-flow-page
- [x] add a dynamic link to the flow-card
- [x] add local storage to save data from the form (state "flows")
- [x] change the static flow page to a dynamic page and use the data from local storage
