### ISSUE TITLE
User Story 11: add navigation 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#22]
## Value Proposition
As a user I want to use a navigation so that I can navigate between different pages. 

## Description
![Wireframe_CP_US11](https://user-images.githubusercontent.com/111566392/197573693-7b1dadf7-100c-42d8-82ba-7453023e7b48.png)

## Acceptance Criteria
- [ ] display a navbar at the bottom of every page
- [ ] display two NavIcons
- [ ] when clicking on the NavIcon the user is redirected to the to the respective site
- [ ] the navbar should indicate which page the user is on 

## Tasks
- [ ] add a NavBar component
- [ ] add icons to the NavBar
- [ ] add links to the icons 
- [ ] add active prop and conditional styling to the NavBar Items 
- [ ] create a Layout component 
- [ ] add Navbar to Layout component 
- [ ] add Layout component to _app.js

**Comment by Roland-Hufnagel** [comment]
I cannot see a reason for navigation until you dont have content for the 'homepage'.

**Comment by CathrinTruchan** [comment]
Hi @Roland-Hufnagel, thanks for reviewing my user stories :) 
I list all the asanas on the homepage, so there is content. But I am still not sure if I leave it this way or if the "create-flow"-page will be the homepage ;) Maybe I will have this user story on hold until I figure this out.
