### ISSUE TITLE
User Story 12: add description to a flow 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#27]
## Value Proposition
As a user, I want to be able to add a short description to every flow in order to store some information about it. 

## Description
![Wireframe_CP_US12](https://user-images.githubusercontent.com/111566392/198972843-70e8949e-adb8-4fcc-8144-c0966890f87b.png)

## Acceptance Criteria

- [x] in the dynamic flow-page the user should be able to add a short description
- [x] it is optional to add a description
- [x] if a description is added, it is displayed below the name and above the poses 
- [x] the description can be edited any time by clicking on a small edit button

## Tasks
- [x] add a link "add description" and an icon the to the page
- [x] create an input field (type text) to add the description 
- [x] add conditional rendering, so that input field only shows, when icon/link is clicked
- [x] catch the data on submit and add it to the flow-object (property description)
- [x] display the description on the page with edit button

**Comment by PhilippWeiss85** [comment]
Hey Cathrin, nice story. I think you got one duplicate task?
 add conditional rendering, so that input field only shows, when icon/link is clicked
 add logic to open the input field, when edit button is clicked

**Comment by CathrinTruchan** [comment]
> Hey Cathrin, nice story. I think you got one duplicate task? add conditional rendering, so that input field only shows, when icon/link is clicked add logic to open the input field, when edit button is clicked

Hey Philipp, yes you are right :) Thanks for the hint!
