### ISSUE TITLE
User Story 13: delete a flow 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#28]
## Value Proposition
As a user I want to be able to delete a flow, if I don't need it anymore. 

## Description
![Wireframe_CP_US13](https://user-images.githubusercontent.com/111566392/198976219-e4c288f2-7959-4d09-8d1a-37396d895a54.png)

## Acceptance Criteria
- [ ] a delete icon is shown on every flow card
- [ ] when the user clicks on the icon, the flow is deleted from the page 

## Tasks
- [ ] add delete icon to flow card component 
- [ ] add onClick handler to remove the flow from the array and the local storage
