### ISSUE TITLE
User Story 14: edit duration 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#29]
## Value Proposition
As a user, I want to be able to edit the duration of a flow, after I created it, in case I want to change it. 

## Description
![Wireframe_CP_US14](https://user-images.githubusercontent.com/111566392/198987912-17e378d3-5537-4840-95df-9edd6d6eab21.png)

## Acceptance Criteria
- [ ] when the user clicks on the edit icon, he can edit the hours and minutes of the duration
- [ ] the new duration is shown, after clicking the save button

## Tasks
- [ ] add an edit icon to the duration 
- [ ] add onClick handler to it, that displays a form for hours and minutes
- [ ] after submitting the form, catch the data and update the flow-object in the state
