### ISSUE TITLE
User Story 2: Display detailed information for every yoga pose 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#3]
## Value Proposition

As a user, I want to click on the pose to see detailed information, so that I can learn more about every pose.

## Description
Add link:
![Wireframe2_CP_US2](https://user-images.githubusercontent.com/111566392/196126287-f0b6995b-7f70-4938-b20b-8bd8e03693d8.png)
Detail page:
![Wireframe_CP_ US2](https://user-images.githubusercontent.com/111566392/196125089-e3f9e2d8-2d8b-453b-8c7f-7f78e26e66c9.png)

## Acceptance Criteria

- [x] display "show more"-link in every card in the index.js / overview page
- [x] after clicking on the link the user is directed to the detail page of this pose
- [x] detail-page displays more information about every pose 
- [x] information should contain the english name, the sanskrit name, a short description, the level and benefit of the pose

## Tasks
- [x] create a detail page and a component for the detail-card, that displays the required information
- [x] implement dynamic routing 
- [x] add dynamic link element to the card-component

**Comment by PhilippWeiss85** [comment]
Hello, nice userstory!

**Comment by CathrinTruchan** [comment]
> Hello, nice userstory!

Grazie :)
