### ISSUE TITLE
Restructuring the app

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#34]
## Value Proposition
As a user I want an app with a logical and clear structure in order to have a good user experience. 

## Description
//

## Acceptance Criteria

- [x] the user should start with creating a new flow, so the create page should be the homepage 
- [x] there should be no pages that have no benefit for the user
- [x] there should be a header for better UX 

## Tasks
- [x] move the content from create/index.js to index.js
- [x] delete flow/index.js
- [x] add header component and implement it into a layout component

**Comment by Kheirah** [comment]
Housekeeping 🧹😄 👍

**Comment by CathrinTruchan** [comment]
> Housekeeping 🧹😄 👍

Haha yes, exactly!
