### ISSUE TITLE
component testing 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#35]
## Value Proposition
As a developer I want to make sure, that all my components work as they should in order to give the user a good UX.

## Description
// 

## Acceptance Criteria
- [ ] component testing for main features

## Tasks
- [ ] write a test for the create-flow form component
- [ ] write a test for rendering the asana list 
- [ ] write a test for the delete-flow button

**Comment by Kheirah** [comment]
Testing incoming, very good! 👩‍💻
