### ISSUE TITLE
Connect MongoDB

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#36]
## Value Proposition

As a user I want to store my data securely so that a can have access to it at any time. 

## Description
// 

## Acceptance Criteria
- [ ] a MongoDB database 
- [ ] the database contains 2 collections: asanas and flows 
- [ ] a connection to the database via API 

## Tasks
- [ ] create a new feature-branch feat/mongoDB
- [ ] create a new database called "Your daily flow"
- [ ] create a collection for asanas and transfer data from db.js
- [ ] create a collection for flows and transfer dummy-data from db.js
- [ ] install mongoose
- [ ] create .env.local file and set URI 
- [ ] create a lib folder and a dbConnect.js file and set up the connection 
- [ ] create models with mongoose for asanas and flows
- [ ] create service functions for to read / create / update and delete (getAllAsanas, getAsanasByID, createFlow, updateFlow, deleteFlow, getAllFlows, getFlowByID)
- [ ] create API endpoints
- [ ] replace local storage with API call

**Comment by Roland-Hufnagel** [comment]
Good userstory. Have fun implementing it....

**Comment by CathrinTruchan** [comment]
> Good userstory. Have fun implementing it....

Thanks, @Roland-Hufnagel. I sure will have "fun" 😅
