### ISSUE TITLE
User Story 3: Add yoga pose to current flow 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#4]
## Value Proposition
As a user, I want to add and remove particular poses to a sequence, so that I can create my personal yoga flow.
 
## Description

Add toogle-button to card:
![Wireframe1_CP_US3](https://user-images.githubusercontent.com/111566392/196135277-db069671-9999-483a-9c25-da50753a7575.png)
My-Flow-Page:
![Wireframe2_CP_US3](https://user-images.githubusercontent.com/111566392/196135296-ada84f8d-7d52-4a54-98ed-262560e9a442.png)

## Acceptance Criteria

- [ ] a button is added to the card, so that the user can add and remove this pose to the flow 
- [ ] the added poses are displayed in a new page "my flow"
- [ ] a button is added to the my-flow page to reset the whole flow 

## Tasks
- [ ] create a toggle-button to add and remove poses to a state
- [ ] add conditional styling to the toggle-button  
- [ ] add the toggle-button to the card component 
- [ ] create a new page "my flow" 
- [ ] display all poses that are added to the flow 
- [ ] create a button, that removes all poses from the current state

**Comment by F-Kirchhoff** [comment]
Hey Cathrin, in this user story somethings don't add up for me. How can users add specific poses? Is there a form or is that planned as an additional user story later on? If yes, please remove the button for now. 

In one wireframe the card has a plus icon, in the other the card has minus buttons, these seem to stand in conflict.

I would suggest to split this user story in 4 user storys, where for the first 3 you only display a single flow on your app and thats it:
- add assana
- remove assana
- reset flow
- display multiple flows in another page with routing to individual flow sub pages
