### ISSUE TITLE
Styling: final round 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#40]
## Value Proposition
As a user I want to see a nicely designed startpage in order to have a good user experience and use the app more often. 

## Description

![Wireframe_CP_US_styling](https://user-images.githubusercontent.com/111566392/200591577-5fd0b374-3642-4137-8ddf-2609f78583d6.png)

## Acceptance Criteria
- [x] start with a little animation / picture 
- [x] no clickable elements should overlap each other 

## Tasks
- [x] add animation to index.js
- [x] display h1 above animation
- [x] user is redirected to the flow, after creating it
- [x] change position of add-flow button, so that it can not overlap the edit or delete icon of the card
