### ISSUE TITLE
Add user authentication & login 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#41]
## Value Proposition
As a user I want to login into my personal account so that not everyone can see the flows I have created.

## Description

![Wireframe_CP_US-Login](https://user-images.githubusercontent.com/111566392/200589985-34b0fcb1-6599-4cae-adb3-f63e935b4632.png)

## Acceptance Criteria
- [x] the homepage displays a user login
- [x] the user can login with his github credentials 
- [x] once the user has logged in, he has access to the flows he has created and can create new ones

## Tasks
- [x] create a new branch feat/login
- [x] create a login component and add it to the homepage 
- [x] install and set up NextAuth
- [x] configure OAuth App in GitHub
- [x] use useSession-Hook to check for valid sessions
- [x] add new property to the flow-object: user 
- [x] add user identification feature (e.g. email) to the flow-object, when the flow is created 
- [x] only allow access to the flows and to the create form, when session and identification are ok
- [x] conditionally render login / logout button

**Comment by PhilippWeiss85** [comment]
lgtm!
