### ISSUE TITLE
Feature: share flows

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#43]
## Value Proposition
As a user I want to decide, if I want to make a flow public and share it with other users or if the flow should be only for me. 

## Description
//

## Acceptance Criteria
- [ ] when the user creates a flow, he can decide wether it's a private or shared flow 
- [ ] the private flows can only be seen by the user who has created them 
- [ ] every user can see the shared flows 
- [ ] only the user who created the shared flow can edit or delete it 

## Tasks
- [ ] create a new feature branch feat/share-flows
- [ ] add a new property "isShared" to the flow mongoose model 
- [ ] add a checkbox "share flow" to the createFlowForm 
- [ ] submit the information if isShared is true or false in the request.body to mongoDB
- [ ] add a new page "shared flows" that can be accessed by every user
- [ ] getAllFlows by ServerSideProps 
- [ ] filter for isShared property and display only shared flows
- [ ] add navigation for the new page

**Comment by sebsch1337** [comment]
Nice! Sounds simpler than i thought :)
