### ISSUE TITLE
User Story 3: create flow page 

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#5]
## Value Proposition
As a user I want to have a page where I can see my individual flow to practice it.

## Description

![Wireframe CP_US3](https://user-images.githubusercontent.com/111566392/196148016-64278f89-0a5e-4894-b87b-27283d1bd844.png)

## Acceptance Criteria
- [ ] display new page "my flow"
- [ ] poses of my flow are displayed

## Tasks
- [ ] create an new page "my flow"
- [ ] display first "fake flow" with some poses

**Comment by gacsphere** [comment]
Nice! :)
