### ISSUE TITLE
User Story 4: add poses to my personal flow

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#6]
## Value Proposition
As a user I want to select yoga poses so that I can create my individual flow.

## Description
![Wireframe_CP_US4](https://user-images.githubusercontent.com/111566392/196194399-a0814c8c-c128-4eb2-8acd-c0311f7f8b27.png)

## Acceptance Criteria
- [x] display button "create flow"
- [x] after the button has been clicked, display a list of all yoga poses 
- [x] display an add-button for every pose
- [x] display a counter with the number of added yoga poses
- [x] add a functionality to close the list of yoga poses
- [x] display cards of the selected poses, after create-flow-button has been clicked

## Tasks
- [x] add the "create flow" button
- [x] add list with all poses 
- [x] add link "add to flow" to every pose and implement logic to add a pose to a state, when link is clicked
- [x] implement logic, so that the list only shows, when the user clicks on the button "create flow"
- [x] add close-button to the list 
- [x] add a new state for the counter functionality and add the counter variable to the list-section
- [x] map over the state and render the selected poses

**Comment by CathrinTruchan** [comment]
> I checked it carefully and it looks very good to me! 🤩

Thanks, Kai!!

**Comment by F-Kirchhoff** [comment]
Hey Kathrin, same here, looks very good. I wonder if the ux will work out this way, please don't shy away to change it in the future if you feel that there might be a better way of adding asanas to a new flow.

**Comment by CathrinTruchan** [comment]
> Hey Kathrin, same here, looks very good. I wonder if the ux will work out this way, please don't shy away to change it in the future if you feel that there might be a better way of adding asanas to a new flow.

Thanks, Felix. I agree ;) It is just a first draft and I want to change the look in another user story.
