### ISSUE TITLE
User Story 5: add reset flow button

### ISSUE THREAD

**Issue by CathrinTruchan** [CathrinTruchan/capstone-project#7]
## Value Proposition
As a user I want to reset the flow in order to create a new one.

## Description
![Wireframe_CP_US5](https://user-images.githubusercontent.com/111566392/196200473-c4610f06-891b-45d9-a554-1fe3cd35f09f.png)

## Acceptance Criteria
- [x] display a button below the asana list on the flow-page "reset my flow"
- [x] when button is clicked, the flow will be reset and no poses are shown

## Tasks
- [x] create new feature-branch
- [x] create a button component to reset the flow
- [x] implement onClick function: when the button is clicked, the state with the poses is reset to an empty array.

**Comment by Roland-Hufnagel** [comment]
A nice and short userstory. No more questions. Approved!

**Comment by CathrinTruchan** [comment]
> cool user story. Can you explain a bit more how you delete it and then the data is saved? :)

The selected poses are stored in a state. When the user clicks the reset-button that state is reset to an empty array. 
Saving the flow for later is another user story.
I'm not sure if that answers your question ;)

**Comment by philmetscher** [comment]
> > cool user story. Can you explain a bit more how you delete it and then the data is saved? :)
> 
> The selected poses are stored in a state. When the user clicks the reset-button that state is reset to an empty array. Saving the flow for later is another user story. I'm not sure if that answers your question ;)

yeah but u should implement that into this description 😉
